### PR TITLE
Update/18.14.0

### PR DESCRIPTION
**Pull request by cbouss**
Changes:
- Update to LTS 18.15.0
- Update about section
- Update build scripts for ppc64le
- Disable internationalization until we get a higher icu version on distro (this is to allow compatiblity with jupyterlab and the like)

https://github.com/nodejs/node/tree/v18.15.0
https://nodejs.org/en/blog/release/v18.15.0

https://anaconda.atlassian.net/browse/PKG-1481
https://anaconda.atlassian.net/browse/PKG-610

### CODE REVIEW

**Review by ELundby45 — APPROVED** [review]
I don't _love_ the permissive flag. But if others ok with it, works for me 👍

**Review by skupr-anaconda — APPROVED** [review]
I'm not familiar with the flag `-fpermissive` and why we add it but overall it looks good

**Review by varlackc — APPROVED** [review]
LGTM

**Comment by cbouss** [comment]
In the end I replaced -fpermissive by a more proper patch.

**Pull request merged**
